name: issues actions

on:
  issues:
    types: [opened, edited]
  
jobs:
  create-pr-by-issue:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
#       - name: Create Branch
#         run: |
#           git config --local user.name "Frozen"
#           git config --local user.email "1884084+xrdavies@users.noreply.github.com"
#           git checkout -b "branch-issue-${{ github.event.issue.number }}"
          
#       - name: Create content
#         run: |
#           node index.js ${{ github.event.issue.number }} '${{ github.event.issue.body }}'
          
#       - name: Commit changes
#         run: |
#           git add .
#           git commit -m "branch-issue-${{ github.event.issue.number }}"
#           git push --set-upstream origin "branch-issue-${{ github.event.issue.number }}"
          
#       - name: Creating Pull Request
#         run: |
#           echo "${{ secrets.PERSON_TOKEN }}" | gh auth login --with-token
#           gh auth status
#           gh pr create --title "Submite New DAO: ${{ github.event.issue.number }}" --body "PR automatically created" || echo ""
          
      - name: Send to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New Issue Created. ${{github.event.issue.html_url}}
