name: issues actions

on:
  issues:
    types: [opened, edited]

  pull_request:
    types: [opened, synchronize, reopened, closed]
  
jobs:
  create-pr-by-issue:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create content
        run: |
          echo "new dao created" >> dao.json

      - name: Creating Pull Request
        run: |
          echo "${{ secrets.PERSON_TOKEN }}" | gh auth login --with-token
          gh auth status
          gh pr create --title "Submite New DAO: ${{ github.event.issue.number }}" --body "PR automatically created" || echo ""
