name: issues actions

on:
  issues:
    types: [opened, edited]
  
jobs:
  create-pr-by-issue:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Create Content
        run: |
          git config --local user.name "Frozen"
          git config --local user.email "1884084+xrdavies@users.noreply.github.com"
          git checkout -b "branch-issue-${{ github.event.issue.number }}"
          echo "new dao created" >> dao.json
          git add .
          git commit -m "branch-issue-${{ github.event.issue.number }}"
          git push --set-upstream origin "branch-issue-${{ github.event.issue.number }}"
          
      - name: Creating Pull Request
        run: |
          echo "${{ secrets.PERSON_TOKEN }}" | gh auth login --with-token
          gh auth status
          gh pr create --title "Submite New DAO: ${{ github.event.issue.number }}" --body "PR automatically created" || echo ""
